version: '3.5'

services:
  postgres-db:
      build:
          context: .
          dockerfile: ./dockerfiles/postgres.dockerfile
      volumes:
          - postgres-volume:/docker-entrypoint-initdb.d
      environment:
          - POSTGRES_USER=test
          - POSTGRES_PASSWORD=test
          - POSTGRES_MULTIPLE_DATABASES=ai,orthanc
      ports:
          - "5432:5432"
  rabbitmq:
    image: rabbitmq:3.8.5-management
    ports:
      - 5672:5672
      - 15671:15671
      - 15672:15672

  redis:
    image: redis
    ports:
      - 6379:6379

networks:
  default:
    name: ai-network
volumes:
    postgres-volume:
        name: postgres-volume