version: '3.5'

services:
  rabbitmq:
    image: rabbitmq:3.8.5-management
    ports:
      - 5672:5672
      - 15671:15671
      - 15672:15672

  redis:
    image: redis
    ports:
      - 6379:6379

networks:
  default:
    name: ai-network
