apiVersion: v1
kind: PersistentVolume
metadata:
  name: med-ai-orthanc
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/orthanc/
  claimRef:
    name: medai-orthanc-storage
    namespace: default
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - parasai1