apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: medai-ai-images
  name: medai-ai-images
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M

status: {}
