apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (HEAD)
      labels:
        io.kompose.service: ui
    spec:
      containers:
        - image: tclarke104/med-ai-ui:0.1
          imagePullPolicy: Always
          name: ui
          ports:
            - containerPort: 4200
          resources: {}
      restartPolicy: Always
status: {}
