apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (HEAD)
      labels:
        io.kompose.service: server
    spec:
      containers:
        - env:
            - name: LOGSTASH_HOST
              value: logstash
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: ORTHANC_HOST
              value: orthanc
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: REDIS_HOST
              value: redis
          image: tclarke104/med-ai-server:0.1
          imagePullPolicy: IfNotPresent
          name: server
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /opt/images
              name: medai-ai-images
      restartPolicy: Always
      volumes:
        - name: medai-ai-images
          persistentVolumeClaim:
            claimName: medai-ai-images
status: {}
