apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  labels:
    io.kompose.service: server
  name: server
spec:
  type: NodePort
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
      nodePort: 8000
  selector:
    io.kompose.service: server
status:
  loadBalancer: {}
