apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: orthanc-public
  name: orthanc-public
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orthanc-public
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: orthanc-public
    spec:
      containers:
        - image: tclarke104/med-ai-orthanc-public:0.1
          imagePullPolicy: IfNotPresent
          name: orthanc-public
          ports:
            - containerPort: 4242
            - containerPort: 8042
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/orthanc/db
              name: medai-orthanc-storage
      restartPolicy: Always
      volumes:
        - name: medai-orthanc-storage
          persistentVolumeClaim:
            claimName: medai-orthanc-storage
status: {}
