apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  labels:
    io.kompose.service: orthanc-public
  name: orthanc-public
spec:
  type: NodePort
  ports:
    - name: "4242"
      port: 4242
      targetPort: 4242
      nodePort: 4242
    - name: "8042"
      port: 8042
      targetPort: 8042
      nodePort: 8042
  selector:
    io.kompose.service: orthanc-public
status:
  loadBalancer: {}
