# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Runs a set of commands using the runners shell
    - name: Update other Readmes
      run: |
        export GITHUB_USER=j718
        mkdir repos
        git config --global user.name "Jacob Clarke"
        git config --global user.email "jacobclarke718@gmail.com"
        for i in {med-ai-ui,med-ai-models}
        do
        git clone https://${GITHUB_USER}:${{secrets.GHUB_TOKEN}}@github.com/Travis-Med-AI/$i repos/$i
        yes | cp -rf README.md repos/$i/README.md
        cd repos/$i
        git add README.md
        git commit -m "Updated Readme"
        git push
        cd ../..
        done
