apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  labels:
    io.kompose.service: worker-gpu
  name: worker-gpu
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker-gpu
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (HEAD)
      labels:
        io.kompose.service: worker-gpu
    spec:
      containers:
        - image: tclarke104/med-ai-runner-worker-gpu:0.1
          imagePullPolicy: Never
          name: worker-gpu
          resources: {}
          volumeMounts:
            - mountPath: /opt/images
              name: medai-ai-images
          workingDir: /app
      restartPolicy: Always
      volumes:
        - name: medai-ai-images
          persistentVolumeClaim:
            claimName: medai-ai-images
status: {}
